### ISSUE TITLE
Investigate GPU support

### ISSUE THREAD

**Issue by bpmct** [coder/envbuilder#143] opened 2024-04-25 15:10 UTC
Some users will want to mount a GPU to an envbuilder-backed workspace. Can we investigate in which scenarios (if any) this works today and if/how we can patch upstream Kaniko to improve the experience?

## Related

- Kaniko issue: https://github.com/GoogleContainerTools/kaniko/issues/3006
- [Internal Slack message](https://codercom.slack.com/archives/C015YDF37AT/p1714057064019159)

**Comment by mtojek** [comment] 2024-05-09 08:45
@BrunoQuaresma We may need to write a mini-RFC describing the status quo.

**Comment by BrunoQuaresma** [comment] 2024-05-14 12:21
After talk to @mtojek  I think I have a good plan:

- Try to run envbuilder in a regular environment
  - Spin up a regular k8s cluster on Google Cloud
  - Try to run envbuilder with a hello world image and see if it works
- Try to reproduce the user error by running envbuilder with a GPU
  - Spin up a k8s cluster using a NVidia GPU on Google Cloud
  - Try to run envbuilder with a hello world image and see if it works
  - Try to find a workaround
  - Investigate possible solutions using diff builders besides kaniko

**Comment by BrunoQuaresma** [comment] 2024-05-23 15:22
@bpmct I tried to use envbuilder in a GPU environment and it worked as expected. Here is how I made it:
- Spin up a k8s cluster with GPU support on GKE
  - GKE version `1.27.13-gke.1000000`
  - Machine type `n1-standard-4`
  - GPU accelerators (per node) `2 x NVIDIA T4`
- Setup a [test repo](https://github.com/BrunoQuaresma/envbuilder-gpu-test) with devcontainer using a Nvidia test image
  - Example: https://catalog.ngc.nvidia.com/orgs/nvidia/teams/k8s/containers/cuda-sample
  - NVidia example image: `nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2`
- Set the following envbuilder config
  - `GIT_URL` as `https://github.com/BrunoQuaresma/envbuilder-gpu-test`
  - `INIT_SCRIPT` as `/tmp/vectorAdd`
  
@bpmct do you think we can get more details from the user?

**Comment by BrunoQuaresma** [comment] 2024-05-28 13:20
I am closing this for now until we have more context from the user.

**Comment by marrotte** [comment] 2024-05-30 20:36
Try using the NVIDIA k8s device plugin (DaemonSet) and not a NVIDIA container image, e.g.:

https://github.com/NVIDIA/k8s-device-plugin

https://learn.microsoft.com/en-us/azure/aks/gpu-cluster?tabs=add-ubuntu-gpu-node-pool#nvidia-device-plugin-installation

This is the recommended approach when using GPU-enabled node pools for Azure Linux.

**Comment by johnstcn** [comment] 2024-05-31 14:25
> > Try using the NVIDIA k8s device plugin (DaemonSet)

@marrotte FYI while we tested using GKE, the cluster we tested on does use the device plugin. However, it appears to be a customized version for GKE COS, and I will freely admit that cluster is a bit old.

What Kubernetes version are you seeing issues with on AKS? 

> not a NVIDIA container image, e.g.: and not a NVIDIA container image

This container image is the one NVIDIA recommends to test GPU support (c.f. https://github.com/NVIDIA/k8s-device-plugin?tab=readme-ov-file#running-gpu-jobs)

What image would you recommend instead as a test? I note that the Azure docs you linked reference a separate MNIST test image.

**Comment by marrotte** [comment] 2024-05-31 15:34
@johnstcn I'm seeing the issue on:

- K8s Rev: v1.27.7
- Node image:  AKSUbuntu-2204gen2containerd-202401.09.0
- Plugin image: mcr.microsoft.com/oss/nvidia/k8s-device-plugin:1.11
- Pod image = "ghcr.io/coder/envbuilder:0.2.9"

**Comment by nikawang** [comment] 2024-06-13 12:13
@BrunoQuaresma 
Still have issues via using your [test repo](https://github.com/BrunoQuaresma/envbuilder-gpu-test) on AKS agains `ghcr.io/coder/envbuilder:0.2.9`

```
root@coder-daniel-kkk-copy-75f96d6c7b-dxxdn:/# nvidia-smi
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.
root@coder-daniel-kkk-copy-75f96d6c7b-dxxdn:/# cd /tmp
root@coder-daniel-kkk-copy-75f96d6c7b-dxxdn:/tmp# ls
coder.wTqTN7  vectorAdd
root@coder-daniel-kkk-copy-75f96d6c7b-dxxdn:/tmp# ./vectorAdd
[Vector addition of 50000 elements]
Failed to allocate device vector A (error code CUDA driver version is insufficient for CUDA runtime version)!
```

**Comment by nikawang** [comment] 2024-06-13 14:07
Oh, I fixed it by
 ```
echo "/usr/lib64" > /etc/ld.so.conf.d/customized.conf 
ldconfig
```

**Comment by BrunoQuaresma** [comment] 2024-06-13 14:22
@marrotte does the @nikawang fix work for you?

**Comment by marrotte** [comment] 2024-06-17 14:33
@BrunoQuaresma I don't think I can test that as my envbuilder fails to build.  I believe @nikawang either applied that fix to a envbuilder running container or the running container built by envbuilder.  I did try applying @nikawang's fix to the AKS/K8s GPU node as if that might be where it was applied and that had no effect.

**Comment by BrunoQuaresma** [comment] 2024-06-17 19:18
@marrotte could you please share with me how I can set up a similar k8s cluster step by step or a Terraform file where I can just run it?

**Comment by BrunoQuaresma** [comment] 2024-06-21 16:04
I tried to create a Kubernetes GPU cluster on Azure following [this tutorial](https://learn.microsoft.com/en-us/azure/aks/gpu-cluster?tabs=add-ubuntu-gpu-node-pool#use-the-aks-gpu-image-preview), but without success. During the process, I managed to get the cluster up and running and register the required features and services through step five of the tutorial.

```
bruno [ ~ ]$ az feature show --namespace "Microsoft.ContainerService" --name "GPUDedicatedVHDPreview"
{
  "id": "/subscriptions/05e8b285-4ce1-46a3-b4c9-f51ba67d6acc/providers/Microsoft.Features/providers/Microsoft.ContainerService/features/GPUDedicatedVHDPreview",
  "name": "Microsoft.ContainerService/GPUDedicatedVHDPreview",
  "properties": {
    "state": "Registered"
  },
  "type": "Microsoft.Features/providers/features"
}
```

However, when I began adding the node pool, I started encountering errors.

```
az aks nodepool add \
    --resource-group bruno \
    --cluster-name bruno-gpu \
    --name gpunp \
    --node-count 1 \
    --node-vm-size Standard_NC6s_v3 \
    --node-taints sku=gpu:NoSchedule \
    --aks-custom-headers UseGPUDedicatedVHD=true \
    --enable-cluster-autoscaler \
    --min-count 1 \
    --max-count 3
```

```
(OperationNotAllowed) .properties.nodeProvisioningProfile.mode cannot be Auto while any AgentPools have .properties.enableAutoScaling enabled
Code: OperationNotAllowed
Message: .properties.nodeProvisioningProfile.mode cannot be Auto while any AgentPools have .properties.enableAutoScaling enabled
```


I tried searching for the error on Google to find a solution or any information related to `properties.nodeProvisioningProfile.mode`, but I didn't find anything helpful. I realized that it might be better to ask if you could share a Terraform file or a more straightforward tutorial for us to reproduce your environment.

**Comment by maxbrunet** [comment] 2024-06-26 18:42
So `ENVBUILDER_IGNORE_PATHS` can be set to `/dev,/lib/firmware/nvidia,/usr/bin/nv-,/usr/bin/nvidia-,/usr/lib64/libcuda,/usr/lib64/libnvidia-,/var/run`, but we hit the known `unlinkat`/`device or resource busy` error.

The easiest to get the right environment to reproduce is likely the [gpu-operator](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/getting-started.html) for Kubernetes or the [NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/index.html) for Docker.

I believe #183 (and #249) can provide a workaround here by temporarily remounting the path out of the way instead trying to ignore them in Kaniko, although note that mount/umount require privileges.

Currently only read-only mounts are taken care of, but the NVIDIA container runtime mounts `devtmpfs` filesystems at `/var/run/nvidia-container-devices/GPU-<uuid>` (the actual mountpoint can be `/run` since often `/var/run` is a symlink to it), the logic would need to be extended to cover those (I have successfully done that).

The runtime also mounts libraries with symlinks:

```
libcuda.so -> libcuda.so.1
libcuda.so.1 -> libcuda.so.<driver-version>
libcuda.so.<driver-version>
libcudadebugger.so.1 -> libcudadebugger.so.<driver-version>
libcudadebugger.so.<driver-version>
libnvidia-allocator.so.1 -> libnvidia-allocator.so.<driver-version>
libnvidia-allocator.so.<driver-version>
libnvidia-cfg.so.1 -> libnvidia-cfg.so.<driver-version>
libnvidia-cfg.so.<driver-version>
libnvidia-ml.so.1 -> libnvidia-ml.so.<driver-version>
libnvidia-ml.so.<driver-version>
libnvidia-nvvm.so.4 -> libnvidia-nvvm.so.<driver-version>
libnvidia-nvvm.so.<driver-version>
libnvidia-opencl.so.1 -> libnvidia-opencl.so.<driver-version>
libnvidia-opencl.so.<driver-version>
libnvidia-pkcs11-openssl3.so.<driver-version>
libnvidia-pkcs11.so.<driver-version>
libnvidia-ptxjitcompiler.so.1 -> libnvidia-ptxjitcompiler.so.<driver-version>
libnvidia-ptxjitcompiler.so.<driver-version>
```

The symlinks **must** also be preserved. The location in the `envbuilder` image is `/usr/lib64`, but it differs between distros (for example in Debian, it should be `/usr/lib/x86_64-linux-gnu`), so the remount process must discover the appropriate location in the new filesystem hierarchy.

I am using this quick-and-dirty script afterward to get things working:

<details>
<summary>remount_and_resymlink.sh</summary>

```bash
#!/usr/bin/env bash
set -euo pipefail

TARGET=/usr/lib/x86_64-linux-gnu

FIRMWARES=(/lib/firmware/nvidia/*)
VERSION="${FIRMWARES[0]}"
VERSION="${VERSION##*/}"

mount | awk '/\/usr\/lib64/{print $3}' | while read -r path; do
  lib="${path##*/}"

  mkdir -p "${TARGET}"
  touch "${TARGET}/${lib}"
  mount --bind "${path}" "${TARGET}/${lib}"
  unmount "${path}"

  case "${lib}" in
    libnvidia-pkcs11.so.*) ;;
    libnvidia-pkcs11-openssl3.so.*) ;;
    libnvidia-nvvm.so.*)
      n=4
      ;;
    *)
      n=1
      ;;
  esac

  if [[ -n "${n:-}" ]]; then
    ln -s "${lib}" "${TARGET}/${lib%"${VERSION}"}${n}"
  fi

  if [[ "${lib}" == "libcuda.so."* ]]; then
    ln -s "${lib}" "${TARGET}/${lib%".${VERSION}"}"
  fi
done
```

</details>

Once that is all in place, the `nvidia-smi` command should work, the GPU(s) should be visible as well as the CUDA version.

In an image with `pytorch` (e.g. `nvcr.io/nvidia/pytorch:24.05-py3`), `python -c 'import torch; print(torch.cuda.is_available())'` should return `True`.

One thing I have not figured out yet is why the container gets **all GPUs when only 1 is requested** (this works properly for a regular container) 😕 

The manifest I am using at the moment:

<details>
<summary>pod.yaml</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: envbuilder 
spec:
  containers:
  - name: envbuilder
    image: ghcr.io/coder/envbuilder-preview
    env:
    - name: FALLBACK_IMAGE
      value: debian
    - name: INIT_SCRIPT
      value: sh -c 'while :; do sleep 86400; done' 
    resources:
      limits:
        nvidia.com/gpu: "1"
    securityContext:
      privileged: true
```

</details>

If you are on GCP/GKE, the above should be valid for Ubuntu nodes (I think, I am not testing there). I need to investigate on GCP's ContainerOS too since things are wired a little differently.

**Closed** 2024-07-02 08:14 UTC
Labels: enhancement, spike

**Comment by adrianmlops** [comment] 2025-04-10 13:42
Any updates on this?

I've been experimenting with the envbuilder build process using Nvidia GPU images on EKS, and so far, the only way I can get it to succeed is by setting the container as privileged. However, this introduces a significant issue: the container ends up seeing all GPUs on the host, even when only one is requested. This breaks GPU isolation and is especially problematic in multi-user environments where resource separation is critical.

Here’s the security_context I’m currently using:

```
security_context {
  run_as_user = 0
  privileged  = true
}
```

I suspect that enabling privileged = true is bypassing Kubernetes’ standard GPU isolation via the device plugin, but I haven’t found a reliable alternative yet that allows the build to succeed.

Has anyone found a way to:
- Avoid privileged mode while still building successfully with GPU images?
- Or isolate GPU access even when privileged is required?

Any insights would be greatly appreciated!

**Comment by djmcgreal-cc** [comment] 2025-05-23 10:39
Very interested in this, without being able to contribute much.

I *think* that adding `SYS_ADMIN` capabilities to the Pod will allow mount/unmount without breaking GPU isolation?

That doesn't help us much because we can't do either in the target environment. Any chance there's another approach that doesn't require extra privileges?
